### ISSUE TITLE
The connection during switching of LFMs

### ISSUE THREAD

**Issue by chitianqilin** [DiegoAE/HMMLFM#2]
I am wondering how the adjacent segments are connected in this model during switching of LFMs. Is it by LFMHMMcontinuousMO.set_observations? Is the velocity continuous at the switching point? What is the detailed mechanism? 
Thanks

**Comment by DiegoAE** [comment]
For a detailed explanation you can check section 5.1 "Hidden Markov Models and Latent Force Models" of this [master thesis](http://repositorio.utp.edu.co/dspace/bitstream/handle/11059/8055/519233A282.pdf)
In a nutshell, the mean function of the LFM at a particular segment is a constant function equal to the last observation of the segment before it. Additionally, the first observation is conditioned to be equal to that mean constant value.
Regarding the velocities, in the current implementation they are not necessarily continuous at the switching points, only the outputs are.
